# # https://github.com/Yikun/hub-mirror-action
name: 同步到 Gitee
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source codes
        uses: actions/checkout@v2
      - name: sync to gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/pub-go
          dst: gitee/pub-go
          dst_key: ${{ secrets.dst_key }}
          dst_token: ${{ secrets.dst_token }}
          static_list: 'errors'
          debug: true
